use std::path::Path;

use crate::artifacts::{Artifact, Doc};
use crate::config::Project;
use crate::markdown::{self, Align, code, relative};
use crate::package::Example;
use crate::pages::OVERVIEW;

pub fn render(project: &Project, here: &Path, doc: &Doc<'_>) -> Vec<Artifact> {
    if doc.krate.examples.is_empty() {
        return Vec::new();
    }
    let mut pages = vec![Artifact {
        path: here.join(OVERVIEW),
        content: index(doc),
    }];
    pages.extend(doc.krate.examples.iter().map(|example| Artifact {
        path: here.join(format!("{}.md", example.name)),
        content: page(project, here, doc, example),
    }));
    pages
}

pub fn run_command(package: &str, example: &Example) -> String {
    let mut command = format!("cargo run -p {package} --example {}", example.name);
    if !example.features.is_empty() {
        command.push_str(&format!(" --features {}", example.features.join(",")));
    }
    command
}

pub fn table(doc: &Doc<'_>, target: impl Fn(&str) -> String) -> String {
    let rows: Vec<Vec<String>> = doc
        .krate
        .examples
        .iter()
        .map(|example| {
            vec![
                format!("[{}]({})", code(&example.name), target(&example.name)),
                code(&run_command(&doc.surface.package, example)),
            ]
        })
        .collect();
    markdown::table(&[("Example", Align::Left), ("Run", Align::Left)], &rows)
}

fn index(doc: &Doc<'_>) -> String {
    format!(
        "# {} examples\n\nGenerated by truesight from the crate's example targets. Each page shows the source that `cargo` builds.\n\n{}",
        code(&doc.surface.package),
        table(doc, |name| format!("{name}.md")),
    )
}

fn page(project: &Project, here: &Path, doc: &Doc<'_>, example: &Example) -> String {
    format!(
        "# Example {}\n\nRun it:\n\n```sh\n{}\n```\n\nSource: {}\n\n```rust,ignore\n{{{{#include {}}}}}\n```\n",
        code(&example.name),
        run_command(&doc.surface.package, example),
        code(&project.show(&example.source)),
        relative(here, &example.source),
    )
}
