use std::collections::HashMap;

use crate::artifacts::Doc;
use crate::markdown::{Align, code, table};
use crate::members;
use crate::modules::{Group, Module};
use crate::pages::{OVERVIEW, file_name, html, target};

pub fn render(doc: &Doc<'_>, modules: &[Module<'_>], module: &Module<'_>) -> String {
    let surface = &doc.surface;
    let ids = module.anchors();
    let own_file = file_name(module.path);
    let tasks = |path: &str| -> Vec<String> {
        doc.tasks
            .iter()
            .filter(|task| surface.resolve(&task.call).unwrap_or(&task.call) == path)
            .map(|task| task.name.clone())
            .collect()
    };
    let link = |path: &str| -> Option<String> {
        let resolved = surface.resolve(path).unwrap_or(path);
        let (file, anchor) = target(modules, resolved)?;
        Some(if file == own_file {
            format!("#{anchor}")
        } else {
            format!("{}#{anchor}", html(&file))
        })
    };
    let sections = module.layout();
    let mut out = format!("# Module {}\n\n", code(module.path));
    out.push_str(&item_table(&sections, &ids, &tasks));
    for (title, groups) in sections {
        out.push_str(&format!("\n## {title}\n"));
        for group in groups {
            out.push_str(&format!("\n### {}\n\n", code(group.name)));
            if let Some(summary) = group.head.and_then(|head| head.summary.as_deref()) {
                out.push_str(&format!("{summary}\n\n"));
            }
            let full = format!("{}::{}", module.path, group.name);
            out.push_str(&members::render(
                group,
                &members::Context {
                    krate: &surface.name,
                    full: &full,
                    tasks: &tasks,
                    link: &link,
                },
            ));
        }
    }
    out.push_str(&format!(
        "\n---\n\nGenerated by truesight from {} {}. See the [API overview]({OVERVIEW}).\n",
        code(&surface.package),
        surface.version
    ));
    out
}

fn item_table(
    sections: &[(&'static str, Vec<&Group<'_>>)],
    ids: &HashMap<&str, String>,
    tasks: &dyn Fn(&str) -> Vec<String>,
) -> String {
    let rows: Vec<Vec<String>> = sections
        .iter()
        .flat_map(|(_, groups)| groups.iter())
        .map(|group| {
            let anchor = ids.get(group.name).map_or("", String::as_str);
            let description = group
                .head
                .map(|head| members::description(head, &tasks(&head.path)))
                .unwrap_or_default();
            vec![
                format!("[{}](#{anchor})", code(group.name)),
                group.kind(),
                description,
            ]
        })
        .collect();
    table(
        &[
            ("Item", Align::Left),
            ("Kind", Align::Left),
            ("Description", Align::Left),
        ],
        &rows,
    )
}
